github: TariqMehmood1004
twitch: ["https://dashboard.twitch.tv/u/tariqmehmood023"]
twitter: ["https://x.com/_tariqsay"]
ko_fi: null
tidelift: null
community_bridge: null
liberapay: null
issuehunt: null
otechie: null 
Buy me a coffee: ["https://buymeacoffee.com/tariqmehmood"]
